### ISSUE TITLE
Video inference script has a possible memory leak

### ISSUE THREAD

**Issue by RohaanA** [yastrebksv/TennisCourtDetector#3]
Hi,

I was successfully able to run the given model after running into several roadblocks,

however I noticed that the given video inference script seems to crash when I upload my larger video (around 1 min length / 60 MB in size)

I don't get any error, but colab reports that the cell was killed with SIGKILL 9.

```
python infer_in_video.py --model_path model_tennis_court_det.pt --input_path large_sample_720p.mp4 --output_path large_sample_output.mp4
' died with <Signals.SIGKILL: 9>.
```

I searched it up a bit on google, and I think it might be related to some sort of memory leak within the script.

**Comment by yastrebksv** [comment]
I suppose this error comes from memory leak. I would recommend you to split large input video into several small parts, run them and combine results.

**Comment by RohaanA** [comment]
I see, that is always a possible approach. Also, I see that the dataset this model was trained on was 720p,am and hence the model fails to plot the points correctly on 1080p images/video. Do you have any idea on how I can make it perform better on 1080p?

**Comment by yastrebksv** [comment]
The resolution of images in dataset is 1280×720. To speed up training process the resolution was reduced to 640x360. You can change your video resolution to appropriate shape, run model and adjust predictions.
