### ISSUE TITLE
Training computational cost

### ISSUE THREAD

**Issue by AkaCoder404** [yastrebksv/TennisCourtDetector#5]
Hey, great work! I was wondering how long and with hardware what you trained on to get the performance of the model you provided. I was able to get this working with YoloV8 through some conversion of the datapoints, which was a much faster training process. So I was wondering how many epochs it took for you to get to the level of performance using your model.

With 10 epochs. Batchsize 8. These are my training results.

<img width="479" alt="image" src="https://github.com/yastrebksv/TennisCourtDetector/assets/45163340/dde391d6-19f3-4907-a743-484e634a47f3">

<img width="779" alt="image" src="https://github.com/yastrebksv/TennisCourtDetector/assets/45163340/3b6e8e1e-821d-4dbb-90d9-fe7bfc0a2eb2">

And performance.
![image](https://github.com/yastrebksv/TennisCourtDetector/assets/45163340/e3d794aa-b5f8-4294-b617-33dd8b48e9e1)

Thanks!

Also, if you wouldn't mind, I could make a pull request and include my Yolov8 model implementation to this repository.

**Comment by yastrebksv** [comment]
Hello. It took me about 15 hour (~330 epochs) to get the model I provided with my RTX 3090.
What final accuracy and precision did you get using YoloV8? I suppose 10 epochs is not enough to train a model.

**Comment by AkaCoder404** [comment]
I was able to achieve the following. 10 Epochs, 16 batches, Imgsize 640. 
```
map50-95 0.9949999999999999
map50 0.995
```

All hail Yolov8 :). Thanks for the response. I uploaded basic code [here](https://github.com/AkaCoder404/TennisCourtDetectorwithYolov8) if you want to check it out.
