### ISSUE TITLE
Why court proportion is different from wikipedia?

### ISSUE THREAD

**Issue by RomaKoks** [yastrebksv/TennisCourtDetector#6]
https://en.wikipedia.org/wiki/Tennis_court

23.77 m / 10.97 m = 2.166818596171376 (for 2 players)

but in your code:
https://github.com/yastrebksv/TennisCourtDetector/blob/582d2be1b93c81bb0800f48678d9d3fc749dbabd/court_reference.py#L51

2408 / 1117 = 2.155774395702775

And what unit of measurement is used?

**Comment by yastrebksv** [comment]
In your calculations you did not take into account the width of white lines. In general the width of white lines is 0.1 m therefore 23.78 m + 3 * 0.1 m = 24.08 m 
10.97 m + 2 * 0.1 m = 11.17 m

**Comment by RomaKoks** [comment]
That is, the measurements indicated in the wiki are not for the outer border?
It seemed to me that the width of the lines is included in this size, especially middle line.
So, then why line width = 1 in code?

Anyway, thanks a lot, I got the answer.
